os: linux
dist: focal
language: java
jdk: openjdk17
cache:
  directories:
    - "$HOME/.m2"
branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: VgBxV0BaO/PEHABJfe4YDirQoZpt4JilnSbE+OlaZUF/kafQa3FXDRWpKkvjPwBwcAgzUW7v274dxwvfEitqqdiqSsEHEBJSvjJwaf4IapOKmqBu0K2+zFqqdUtK+T/tkoU6d8yNIOImgrzKbpAsn4t39ZNbVASyySWUipz8o7SpdvdRlydMkARFiSBxk8fRemcJSpQHUmhngUmtxpMxRLX05WFbu3rwidZ2ky7nv0CqOpWyD0pNsHIemtDb0AiQ/ZAcnOGx4HjsWhwXWl4eJM+JbByT+gpZDRjahMn5UkeMFCZOuiN4CNOrsyjaXiPIlVDxrmZEf6w8NmhY4X0wahF/B/xCMRLY6e5X2YzDNQVOSalrAGnGEIsCR5bDTkiWXjkG/Zzbx+5gyIhv6JMBvysG3s7pQOvV84pG2aq62MprhtBMMpRRl/4sklfWW2LhXK/LWwdCHlW5JmKPCAFMhKNRWUvmYv5WC1CTi8ZCs5zDt+FPe+TOdxD1TqM+yhK/Sn5OCtGu4Gtm9FZwFmqlrD463EBCsjjnsjxSBQiy1FvcGozY2SM42VfqapTP3kgCgAuFEptJw9HfIuoceiIVhnaPETspEnm7kKvBY0iybIH5Fnc/ZXY1QCYhnMqlAtpYvyVl18gpI8ioqWUj74PK7sEvEtd+farIb/EVodvXJ3s=
script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=molgenis_vkgl-consensus
deploy:
  provider: releases
  token:
    secure: DBah++7OFK7YPe6G8bvFasfCxJKe6nQe+O9IgldRVg4ff13pSt5PwqG6Rum6JeXNBGvpnLrwcvdbrp69e8sU/n2GNI2HVdwOmsdurI7QW72CfMyP2LuwIsl5w72Ovvc3Ck7yn28UQzTdqwVAXFDSAMxFvHKgBlNLM+3TGFG2XSU/OcbB02DMWMZajUFbBe8XsKmXxh6meFQ4nLZhecBdsUz0VkOFbnabQ6fYTwu/nO93BRtnam1j9CWONsQAL2z0hAqEHNrGNhphdAaKGXS94aSixPG2FjC3p8kMTc5OUy0vP2TzbdAw7/wPY+V1iuKSvs6L7jj7yXQz7Su2ZYpKrG1x0+tT/o4/sqnYr8a9/yyfsJbf5dniUh9BhvlxXnnZyxQ8t0Qx6KBdQ0FjZ/IGRJIIGh5bnL8CqxwniSvaL0orjYNxhqfVQUDAinUgfq0wYAgMIKqHZEP4gWOueo2QOax2NJg3zEfZi2jK+OQba3oTkULFqE3um1GyVwLhrTRKeCQrfcSKppbvZJPpDcFGqWfvLwrnXxRrdcnfdBOuAtEJgg4brKFdk7rjjr4U6CUCJ3IFM7SafLBp8zFLS84JGRvJvJYcxjOF9PXrgJfybhgU20Kw/9Gn1sBQwQI14L039D8EM7RqsoX6xIGsnoE24Xq56t8N2C7LCzZX3t2h0go=
  file: target/vkgl-consensus.jar
  prerelease: true
  on:
    tags: true
  edge: true # opt in to dpl v2
