os: linux
dist: bionic
language: java
jdk: openjdk11
cache:
  directories:
    - "$HOME/.m2"
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: VgBxV0BaO/PEHABJfe4YDirQoZpt4JilnSbE+OlaZUF/kafQa3FXDRWpKkvjPwBwcAgzUW7v274dxwvfEitqqdiqSsEHEBJSvjJwaf4IapOKmqBu0K2+zFqqdUtK+T/tkoU6d8yNIOImgrzKbpAsn4t39ZNbVASyySWUipz8o7SpdvdRlydMkARFiSBxk8fRemcJSpQHUmhngUmtxpMxRLX05WFbu3rwidZ2ky7nv0CqOpWyD0pNsHIemtDb0AiQ/ZAcnOGx4HjsWhwXWl4eJM+JbByT+gpZDRjahMn5UkeMFCZOuiN4CNOrsyjaXiPIlVDxrmZEf6w8NmhY4X0wahF/B/xCMRLY6e5X2YzDNQVOSalrAGnGEIsCR5bDTkiWXjkG/Zzbx+5gyIhv6JMBvysG3s7pQOvV84pG2aq62MprhtBMMpRRl/4sklfWW2LhXK/LWwdCHlW5JmKPCAFMhKNRWUvmYv5WC1CTi8ZCs5zDt+FPe+TOdxD1TqM+yhK/Sn5OCtGu4Gtm9FZwFmqlrD463EBCsjjnsjxSBQiy1FvcGozY2SM42VfqapTP3kgCgAuFEptJw9HfIuoceiIVhnaPETspEnm7kKvBY0iybIH5Fnc/ZXY1QCYhnMqlAtpYvyVl18gpI8ioqWUj74PK7sEvEtd+farIb/EVodvXJ3s=
script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=molgenis_vkgl-consensus
deploy:
  provider: releases
  token:
    secure: yW89L3sRuO4JBCeG2WCZeqvQW0VJLQnbO4p8J367ZMTxMyqaVycLJpM/9hwIPgN7bIkb1A8QaY/+WU6q8aX2fT06g3OvFCd3FVWtQVOghqwtnT5A6lik1Os1elgi2We3nvdJqNPMfK8HcSGPoybvs/DrXAupugMLXQwOPLSkzdGdyVuLmvllCIoW7ixNGmZYAfVeCjNM9bPr9iUvA3B9NBPBswyLfOPv7W2LHD5EClZEOfoJQG2U/6+a9oFnKjf2gQfKNKwm1S0VKd5aspE9ct7/2R0QGmAERHTOcaG6KZE15bRuc/fl/WnRKgf2koawwkXd9EMpfiCS4CPx+QREq/A6ULCeBQgl+0dRy0th9VKLv5iDl8XBepb/bC09SAXGfhKt+WqwNPqUy0Zx8/U0PyMutfsWvGjlFREG+h2Mlmk1ZLV4VRb1kG74giBzYbJaX7c/o9sYdDv+28UNdIMWTUwFwwnQ26yNKZNY/KdY1xhEZMLhVHE9YPgyC26KkKBpC8hT81gxs0HKYUtdqdMA5FJHY1IRM/dYY3mUrD38lK00U53YhyXB0drotoSjCP5+RcFUF2Sa+ti8X8wbEtxQ/0r2PlibtZ82uHWRAsniJiU0vFKlwmAt8K13rD5LF6fzb3nY7GA8RXQinLx3TPzixFFN/wxDXVx9U7LGL1NKHyI=
  file: target/vkgl-consensus.jar
  prerelease: true
  on:
    tags: true
  edge: true # opt in to dpl v2
