os: linux
dist: bionic
language: java
jdk: openjdk11
cache:
  directories:
    - "$HOME/.m2"
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: IN7WxXSV2xcmNqFyFmBlTu4goHysyKzjY+S+iYG1TD/oF3pvOkO9qj0HXO7rTW0XzsVTJSEww5vB5JCgQVBQHGfqJ80pj8vKomUvpV0iT7x7eTaO8M8n97HkZySXFezDbi5t9iYznd7ulu08fj3iMxUmrtwUgC/NCsbx5qphnVl+TZWPEcrTiqsJnd2jikohe17S8jlyK0wAaJ+h4eud93qJT91hnaOoz97I+qr5cnkmSMMyryR0Wl8yWwpiUyEPJAJ0ISkAah7q0Ib7Xb4wpuGAbYiTD078XDiYzTrBH/BMKYx4s0fyOCyHYKrWxhKkl+8Zk0jzcP8Cw7Y3LfWU2e/catbXt+roni3ntoLHRus1nFMk6cqmp2QB36Dn1Z+UtYQU8rX1eJ3NPpBMZ/diqESsPpHUzot47LIBp4PZ9dQcvu9DLPYFx7wB0+cBkGEwDkA2EfgR+KIWaCr9DhUJlu4kk8qrq/7hukmo9ZhaqZfDI5uwhNZ9aFoxk/gUhPr1kQQczImzFk9Ok9yKNL3cgmXobhuZjeKKshrIoU+sbgGrDak7Pc9NDIL77ysYoFD3XWnlKIDOIOgkS02d/L8MLTg1q9Jxli2gDpElfMedxwOwtGf0ySI6sBLgRX/gd9G7X3tmLq96pOw+LhJ6deg/M1uFMTtcA8vh9NZvHYlK6u8=
script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=molgenis_vkgl-consensus
deploy:
  provider: releases
  token:
    secure: yW89L3sRuO4JBCeG2WCZeqvQW0VJLQnbO4p8J367ZMTxMyqaVycLJpM/9hwIPgN7bIkb1A8QaY/+WU6q8aX2fT06g3OvFCd3FVWtQVOghqwtnT5A6lik1Os1elgi2We3nvdJqNPMfK8HcSGPoybvs/DrXAupugMLXQwOPLSkzdGdyVuLmvllCIoW7ixNGmZYAfVeCjNM9bPr9iUvA3B9NBPBswyLfOPv7W2LHD5EClZEOfoJQG2U/6+a9oFnKjf2gQfKNKwm1S0VKd5aspE9ct7/2R0QGmAERHTOcaG6KZE15bRuc/fl/WnRKgf2koawwkXd9EMpfiCS4CPx+QREq/A6ULCeBQgl+0dRy0th9VKLv5iDl8XBepb/bC09SAXGfhKt+WqwNPqUy0Zx8/U0PyMutfsWvGjlFREG+h2Mlmk1ZLV4VRb1kG74giBzYbJaX7c/o9sYdDv+28UNdIMWTUwFwwnQ26yNKZNY/KdY1xhEZMLhVHE9YPgyC26KkKBpC8hT81gxs0HKYUtdqdMA5FJHY1IRM/dYY3mUrD38lK00U53YhyXB0drotoSjCP5+RcFUF2Sa+ti8X8wbEtxQ/0r2PlibtZ82uHWRAsniJiU0vFKlwmAt8K13rD5LF6fzb3nY7GA8RXQinLx3TPzixFFN/wxDXVx9U7LGL1NKHyI=
  file: target/vkgl-consensus.jar
  prerelease: true
  on:
    tags: true
  edge: true # opt in to dpl v2
